"""empty message

Revision ID: 8a95a3426e95
Revises: 
Create Date: 2024-01-13 19:09:27.859641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a95a3426e95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longtitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('spooky_score', sa.Integer(), nullable=False),
    sa.Column('spooky_review', sa.String(), nullable=False),
    sa.Column('hospitality_score', sa.Integer(), nullable=True),
    sa.Column('hospitality_review', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations_table.id'], name=op.f('fk_reviews_table_location_id_locations_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_reviews_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['users_table.id'], name=op.f('fk_comments_table_poster_id_users_table')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews_table.id'], name=op.f('fk_comments_table_review_id_reviews_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_table')
    op.drop_table('reviews_table')
    op.drop_table('users_table')
    op.drop_table('locations_table')
    # ### end Alembic commands ###
